### ISSUE TITLE
new flag required

### ISSUE THREAD

**Issue by hamnaz** [TheRealLordFractal/Bip39Helper#4]
program fixed with 12 word output in txt file or stdout for brainflayer
if program set with -w flag for user define word count
example -w 6 mean 6word output in  textfile or stdout output for prainflayer

**Comment by SatoshiNakamotoBitcoins** [comment]
@hamnaz Bip39helper is fixed to 12 words and the other repo of Real Lord Bip39generator you can choose 3, 6 or 12 words output.

When applying Bip39helper with the first version ./bip39helper the output goes directly to the 12words.txt file...when applying with the second version ./bip39helper-LinuxX64 the output goes through stdout for piping directly to brainflayer...

But you want to have a another flag in Bip39Helper to choose from 3,6 or 12 words like is possible with Bip39Generator when I'm understand correct...

**Comment by TheRealLordFractal** [comment]
yep I can add this no problem, I didnt think there was much 2,3,6 word combo's left, the 12 is the standard now.. Anyone have an update on the discord link I will put it in the readme on the main page.  Need valid invite

**Comment by TheRealLordFractal** [comment]
This option has been added as of V1.0.2
